/**
 * PDF Export Service - Pure functions for generating export content.
 * The actual PDF rendering is done client-side via browser print.
 * This service handles content formatting and TXT generation.
 */

/**
 * Build a formatted TXT document from application content.
 */
export function buildTxtDocument(content: {
  coverLetter?: string;
  cvKeywords?: string;
  atsSuggestions?: string;
  generatedCv?: string;
}): string {
  const sections: string[] = [];

  sections.push('\u2550'.repeat(51));
  sections.push('  BEWERBUNGGENIE - German Application Bundle');
  sections.push('\u2550'.repeat(51));
  sections.push('');

  if (content.coverLetter) {
    sections.push('\u2501'.repeat(51));
    sections.push('  ANSCHREIBEN (GERMAN COVER LETTER)');
    sections.push('\u2501'.repeat(51));
    sections.push('');
    sections.push(content.coverLetter);
    sections.push('');
  }

  if (content.cvKeywords) {
    sections.push('\u2501'.repeat(51));
    sections.push('  LEBENSLAUFLISTE (CV KEYWORD OPTIMIZATION)');
    sections.push('\u2501'.repeat(51));
    sections.push('');
    sections.push(content.cvKeywords);
    sections.push('');
  }

  if (content.atsSuggestions) {
    sections.push('\u2501'.repeat(51));
    sections.push('  ATS-OPTIMIERUNG (ATS OPTIMIZATION SUGGESTIONS)');
    sections.push('\u2501'.repeat(51));
    sections.push('');
    sections.push(content.atsSuggestions);
    sections.push('');
  }

  if (content.generatedCv) {
    sections.push('\u2501'.repeat(51));
    sections.push('  LEBENSLAUF-ENTWURF (GENERATED CV DRAFT)');
    sections.push('\u2501'.repeat(51));
    sections.push('');
    sections.push(content.generatedCv);
    sections.push('');
  }

  return sections.join('\n');
}

/**
 * Build HTML content for PDF printing.
 */
export function buildPdfHtml(content: {
  coverLetter: string;
  cvKeywords: string;
  atsSuggestions: string;
  generatedCv: string;
}): string {
  const formatSection = (title: string, subtitle: string, text: string) => `
    <div class="section">
      <h2>${title}</h2>
      <p class="subtitle">${subtitle}</p>
      <div class="content">${textToHtml(text)}</div>
    </div>
  `;

  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BewerbungGenie - German Application Bundle</title>
  <style>
    @page { size: A4; margin: 2cm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #1a1a1a; background: #fff; }
    .header { text-align: center; padding-bottom: 20px; margin-bottom: 30px; border-bottom: 2px solid #059669; }
    .header h1 { font-size: 20pt; color: #059669; margin-bottom: 4px; }
    .header p { font-size: 10pt; color: #666; }
    .section { margin-bottom: 30px; page-break-inside: avoid; }
    .section h2 { font-size: 14pt; color: #059669; border-bottom: 1px solid #d1d5db; padding-bottom: 6px; margin-bottom: 4px; }
    .section .subtitle { font-size: 9pt; color: #6b7280; margin-bottom: 12px; font-style: italic; }
    .content { white-space: pre-wrap; font-size: 10.5pt; line-height: 1.7; }
    .footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #d1d5db; text-align: center; font-size: 8pt; color: #9ca3af; }
    @media print { body { margin: 0; } .section { page-break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>BewerbungGenie</h1>
    <p>AI-Powered German Application Bundle</p>
  </div>
  ${content.coverLetter ? formatSection('Anschreiben', 'GERMAN COVER LETTER', content.coverLetter) : ''}
  ${content.cvKeywords ? formatSection('Lebenslaufliste', 'CV KEYWORD OPTIMIZATION', content.cvKeywords) : ''}
  ${content.atsSuggestions ? formatSection('ATS-Optimierung', 'ATS OPTIMIZATION SUGGESTIONS', content.atsSuggestions) : ''}
  ${content.generatedCv ? formatSection('Lebenslauf-Entwurf', 'GENERATED CV DRAFT', content.generatedCv) : ''}
  <div class="footer">
    Generated by BewerbungGenie — AI-Powered German Application Builder
  </div>
</body>
</html>`;
}

/**
 * Convert plain text to HTML with proper formatting.
 */
function textToHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/^### (.+)$/gm, '<strong style="font-size: 12pt; color: #374151;">$1</strong>')
    .replace(/^## (.+)$/gm, '<strong style="font-size: 13pt; color: #059669;">$1</strong>')
    .replace(/^[-\u2022] (.+)$/gm, '<span style="margin-left: 1em;">\u2022 $1</span>')
    .replace(/^\* (.+)$/gm, '<span style="margin-left: 1em;">\u2022 $1</span>');
}
